name: Weather Alert

on:
  schedule:
    - cron: '30 2 * * *'

  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
        run: python rain_alert.py
